version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm run build
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test